purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7401434
  brandStrength: 1
  lightness: 0.3351254
  brandColors:
    - '#FFFAEA'
    - '#070709'
    - '#7CA0AC'
    - '#D4C4A2'
    - '#36392E'
  rhythmicContrast: 0.3787093
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: raphaelkunz
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4426523
layout_spectrum: 1
